<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCg9ZlSb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCg9ZlSb/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCg9ZlSb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCg9ZlSb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCg9ZlSb\App_KernelProdContainer([
    'container.build_hash' => 'Cg9ZlSb',
    'container.build_id' => '615bba34',
    'container.build_time' => 1758631236,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCg9ZlSb');
