<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYgVwW3\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYgVwW3/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXYgVwW3.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXYgVwW3\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXYgVwW3\App_KernelProdContainer([
    'container.build_hash' => 'XYgVwW3',
    'container.build_id' => '8b2a2c1b',
    'container.build_time' => 1758631393,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYgVwW3');
