<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container53jxOc7\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container53jxOc7/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container53jxOc7.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container53jxOc7\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container53jxOc7\App_KernelProdContainer([
    'container.build_hash' => '53jxOc7',
    'container.build_id' => 'd2db078b',
    'container.build_time' => 1758648876,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container53jxOc7');
