#!/bin/bash

echo "🚀 GitHub Repository Setup Guide"
echo "================================"
echo ""
echo "Your local Git repository is ready with:"
echo "✅ Git initialized"
echo "✅ Initial commit created"
echo "✅ README documentation added"
echo ""
echo "📋 Next steps to connect to GitHub:"
echo ""
echo "1. Go to GitHub.com and sign in to your account"
echo ""
echo "2. Click the '+' icon in the top right and select 'New repository'"
echo ""
echo "3. Repository settings:"
echo "   - Repository name: mcnary_technical_backend"
echo "   - Description: Symfony backend for SEO database management"
echo "   - Make it Private (recommended for business projects)"
echo "   - Don't initialize with README (we already have one)"
echo "   - Don't add .gitignore (we already have one)"
echo ""
echo "4. Click 'Create repository'"
echo ""
echo "5. After creation, GitHub will show you commands to run."
echo "   Copy the commands for 'push an existing repository'"
echo ""
echo "6. Run the commands in your terminal:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/mcnary_technical_backend.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "🔗 Your repository will then be connected to GitHub!"
echo ""
echo "💡 Tip: You can also use SSH if you have SSH keys configured:"
echo "   git remote add origin git@github.com:YOUR_USERNAME/mcnary_technical_backend.git"
