<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditCompetitorRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AuditCompetitorRepository' shared autowired service.
     *
     * @return \App\Repository\AuditCompetitorRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AuditCompetitorRepository'] = new \App\Repository\AuditCompetitorRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
