<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\ClientController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\ClientController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\ClientController'] = $instance = new \App\Controller\Api\V1\ClientController(($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')), ($container->privates['App\\Repository\\OrganizationRepository'] ?? $container->load('getOrganizationRepositoryService')), ($container->privates['App\\Repository\\TenantRepository'] ?? $container->load('getTenantRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\ClientController', $container));

        return $instance;
    }
}
