<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSampleDataCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\GenerateSampleDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\GenerateSampleDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:generate-sample-data', [], 'Generate sample data for the client dashboard (leads, campaigns, case studies)', false, #[\Closure(name: 'App\\Command\\GenerateSampleDataCommand')] fn (): \App\Command\GenerateSampleDataCommand => ($container->privates['App\\Command\\GenerateSampleDataCommand'] ?? $container->load('getGenerateSampleDataCommandService')));
    }
}
