<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportTulsaAttorneysCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\ImportTulsaAttorneysCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\ImportTulsaAttorneysCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:import-tulsa-attorneys', [], 'Import mock Tulsa attorneys data for testing', false, #[\Closure(name: 'App\\Command\\ImportTulsaAttorneysCommand')] fn (): \App\Command\ImportTulsaAttorneysCommand => ($container->privates['App\\Command\\ImportTulsaAttorneysCommand'] ?? $container->load('getImportTulsaAttorneysCommandService')));
    }
}
