<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenPhoneWebhookControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\OpenPhoneWebhookController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\OpenPhoneWebhookController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\OpenPhoneWebhookController'] = $instance = new \App\Controller\Api\V1\OpenPhoneWebhookController(($container->privates['App\\Service\\OpenPhoneApiService'] ?? $container->load('getOpenPhoneApiServiceService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\OpenPhoneWebhookController', $container));

        return $instance;
    }
}
