<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\UserProfileController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\UserProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\UserProfileController'] = $instance = new \App\Controller\Api\V1\UserProfileController(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\AgencyRepository'] ?? $container->load('getAgencyRepositoryService')), ($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\UserProfileController', $container));

        return $instance;
    }
}
