<?php

namespace ContainerCg9ZlSb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyRealTulsaLeadsCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\VerifyRealTulsaLeadsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\VerifyRealTulsaLeadsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:verify-real-tulsa-leads', [], 'Verifies that real Tulsa attorneys leads from Google Places API are in the database with "new_lead" status.', false, #[\Closure(name: 'App\\Command\\VerifyRealTulsaLeadsCommand')] fn (): \App\Command\VerifyRealTulsaLeadsCommand => ($container->privates['App\\Command\\VerifyRealTulsaLeadsCommand'] ?? $container->load('getVerifyRealTulsaLeadsCommandService')));
    }
}
