<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_NegotiatorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'api_platform.negotiator' shared service.
     *
     * @return \Negotiation\Negotiator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.negotiator'] = new \Negotiation\Negotiator();
    }
}
