<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_PaginationOptionsService extends App_KernelTestContainer
{
    /*
     * Gets the private 'api_platform.pagination_options' shared service.
     *
     * @return \ApiPlatform\State\Pagination\PaginationOptions
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.pagination_options'] = new \ApiPlatform\State\Pagination\PaginationOptions(true, 'page', false, 'itemsPerPage', false, 'pagination', 30, NULL, false, false, 'partial');
    }
}
