<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_ErrorListenerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'api_platform.error_listener' shared service.
     *
     * @return \ApiPlatform\Symfony\EventListener\ErrorListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['api_platform.metadata.resource.metadata_collection_factory.cached'] ?? self::getApiPlatform_Metadata_Resource_MetadataCollectionFactory_CachedService($container));

        if (isset($container->privates['api_platform.error_listener'])) {
            return $container->privates['api_platform.error_listener'];
        }

        return $container->privates['api_platform.error_listener'] = new \ApiPlatform\Symfony\EventListener\ErrorListener('api_platform.symfony.main_controller', ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), false, [], $a, $container->parameters['api_platform.error_formats'], $container->parameters['api_platform.exception_to_status'], NULL, ($container->privates['api_platform.resource_class_resolver'] ?? self::getApiPlatform_ResourceClassResolverService($container)), ($container->privates['api_platform.negotiator'] ??= new \Negotiation\Negotiator()));
    }
}
