<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Openapi_SerializerContextBuilderService extends App_KernelTestContainer
{
    /*
     * Gets the private 'api_platform.openapi.serializer_context_builder' shared service.
     *
     * @return \ApiPlatform\OpenApi\Serializer\SerializerContextBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['api_platform.serializer.context_builder.filter'] ?? $container->load('getApiPlatform_Serializer_ContextBuilder_FilterService'));

        if (isset($container->privates['api_platform.openapi.serializer_context_builder'])) {
            return $container->privates['api_platform.openapi.serializer_context_builder'];
        }

        return $container->privates['api_platform.openapi.serializer_context_builder'] = new \ApiPlatform\OpenApi\Serializer\SerializerContextBuilder($a);
    }
}
