<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Symfony_UriVariables_Transformer_UuidService extends App_KernelTestContainer
{
    /*
     * Gets the private 'api_platform.symfony.uri_variables.transformer.uuid' shared service.
     *
     * @return \ApiPlatform\Symfony\UriVariableTransformer\UuidUriVariableTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['api_platform.symfony.uri_variables.transformer.uuid'] = new \ApiPlatform\Symfony\UriVariableTransformer\UuidUriVariableTransformer();
    }
}
