<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBacklinksControllerService extends App_KernelTestContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\BacklinksController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\BacklinksController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\BacklinksController'] = $instance = new \App\Controller\Api\V1\BacklinksController(($container->privates['App\\Repository\\BacklinkRepository'] ?? $container->load('getBacklinkRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\BacklinksController', $container));

        return $instance;
    }
}
