<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSystemAccountCommandService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Command\CreateSystemAccountCommand' shared autowired service.
     *
     * @return \App\Command\CreateSystemAccountCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreateSystemAccountCommand'] = $instance = new \App\Command\CreateSystemAccountCommand(($container->privates['App\\Service\\SystemAccountService'] ?? $container->load('getSystemAccountServiceService')));

        $instance->setName('app:create-system-account');
        $instance->setDescription('Create a new system account for backend operations');

        return $instance;
    }
}
