<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebug_StopwatchService extends App_KernelTestContainer
{
    /*
     * Gets the private 'debug.stopwatch' shared service.
     *
     * @return \Symfony\Component\Stopwatch\Stopwatch
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true);
    }
}
