<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpClient_UriTemplate_InnerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'http_client.uri_template.inner' shared service.
     *
     * @return \Symfony\Contracts\HttpClient\HttpClientInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['http_client.uri_template.inner'] = ($container->privates['http_client.transport'] ?? $container->load('getHttpClient_TransportService'));
    }
}
