<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikJwtAuthentication_PayloadEnrichmentService extends App_KernelTestContainer
{
    /*
     * Gets the private 'lexik_jwt_authentication.payload_enrichment' shared service.
     *
     * @return \Lexik\Bundle\JWTAuthenticationBundle\Services\PayloadEnrichment\ChainEnrichment
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['lexik_jwt_authentication.payload_enrichment'] = new \Lexik\Bundle\JWTAuthenticationBundle\Services\PayloadEnrichment\ChainEnrichment([]);
    }
}
