<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthTokenRepositoryService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Repository\OAuthTokenRepository' shared autowired service.
     *
     * @return \App\Repository\OAuthTokenRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OAuthTokenRepository'] = new \App\Repository\OAuthTokenRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
