<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemAccountServiceService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Service\SystemAccountService' shared autowired service.
     *
     * @return \App\Service\SystemAccountService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SystemAccountService'] = new \App\Service\SystemAccountService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
