<?php

namespace ContainerJ65J2Sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Extension_LogoutUrlService extends App_KernelTestContainer
{
    /*
     * Gets the private 'twig.extension.logout_url' shared service.
     *
     * @return \Symfony\Bridge\Twig\Extension\LogoutUrlExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.logout_url_generator'] ?? self::getSecurity_LogoutUrlGeneratorService($container));

        if (isset($container->privates['twig.extension.logout_url'])) {
            return $container->privates['twig.extension.logout_url'];
        }

        return $container->privates['twig.extension.logout_url'] = new \Symfony\Bridge\Twig\Extension\LogoutUrlExtension($a);
    }
}
