services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\WebCrawler:
        arguments:
            $storagePath: '%kernel.project_dir%/var/storage'

    App\Service\CrawlerService:
        arguments:
            $crawler: '@App\Service\WebCrawler'

    App\Service\SeoAnalyzer:
        arguments:
            $auditRunRepository: '@App\Repository\AuditRunRepository'
            $pageRepository: '@App\Repository\PageRepository'

    App\Service\SeoScorer:
        arguments:
            $auditRunRepository: '@App\Repository\AuditRunRepository'

    App\MessageHandler\CrawlAuditRunMessageHandler:
        tags: ['messenger.message_handler']

    App\MessageHandler\AnalyzeAuditRunMessageHandler:
        tags: ['messenger.message_handler']