<?php

namespace ContainerSYgO7Pj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProvider_ParameterValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'api_platform.state_provider.parameter_validator' shared service.
     *
     * @return \ApiPlatform\Symfony\Validator\State\ParameterValidatorProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/Util/ParameterParserTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/Validator/State/ParameterValidatorProvider.php';

        return $container->services['api_platform.state_provider.parameter_validator'] = new \ApiPlatform\Symfony\Validator\State\ParameterValidatorProvider(($container->privates['validator'] ?? self::getValidatorService($container)), ($container->privates['api_platform.state_provider.access_checker.post_validate'] ?? $container->load('getApiPlatform_StateProvider_AccessChecker_PostValidateService')));
    }
}
