<?php

namespace ContainerSYgO7Pj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditIntakeControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\V1\AuditIntakeController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\AuditIntakeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/V1/AuditIntakeController.php';

        $container->services['App\\Controller\\Api\\V1\\AuditIntakeController'] = $instance = new \App\Controller\Api\V1\AuditIntakeController(($container->privates['App\\Service\\AuditIntakeValidationService'] ?? $container->load('getAuditIntakeValidationServiceService')), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\AuditIntakeController', $container));

        return $instance;
    }
}
