<?php

namespace ContainerSYgO7Pj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditIntakeValidationServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\AuditIntakeValidationService' shared autowired service.
     *
     * @return \App\Service\AuditIntakeValidationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AuditIntakeValidationService.php';

        return $container->privates['App\\Service\\AuditIntakeValidationService'] = new \App\Service\AuditIntakeValidationService(($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')));
    }
}
