<?php

namespace ContainerSYgO7Pj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaqsControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\V1\FaqsController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\FaqsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/V1/FaqsController.php';

        $container->services['App\\Controller\\Api\\V1\\FaqsController'] = $instance = new \App\Controller\Api\V1\FaqsController(($container->privates['App\\Repository\\FaqRepository'] ?? $container->load('getFaqRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\FaqsController', $container));

        return $instance;
    }
}
