<?php

namespace ContainerSYgO7Pj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSystemAccountServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\SystemAccountService' shared autowired service.
     *
     * @return \App\Service\SystemAccountService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SystemAccountService.php';

        return $container->privates['App\\Service\\SystemAccountService'] = new \App\Service\SystemAccountService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
    }
}
