<?php

namespace ContainerC4jAqa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditIntakeClientValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\AuditIntakeClientValidator' shared autowired service.
     *
     * @return \App\Validator\AuditIntakeClientValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/AuditIntakeClientValidator.php';

        return $container->privates['App\\Validator\\AuditIntakeClientValidator'] = new \App\Validator\AuditIntakeClientValidator(($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')));
    }
}
