<?php

namespace ContainerC4jAqa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityInvoiceApiPlatformDoctrineOrmFilterRangeFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'annotated_app_entity_invoice_api_platform_doctrine_orm_filter_range_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\RangeFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/PropertyAwareFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/ManagerRegistryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/RangeFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/OpenApiParameterFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/RangeFilterTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/RangeFilter.php';

        return $container->privates['annotated_app_entity_invoice_api_platform_doctrine_orm_filter_range_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\RangeFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['amount' => NULL, 'taxAmount' => NULL, 'totalAmount' => NULL], ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)));
    }
}
