<?php

namespace ContainerC4jAqa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateClientCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateClientCommand' shared autowired service.
     *
     * @return \App\Command\CreateClientCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateClientCommand.php';

        $container->privates['App\\Command\\CreateClientCommand'] = $instance = new \App\Command\CreateClientCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-client');
        $instance->setDescription('Create a new client (law firm)');

        return $instance;
    }
}
