<?php

namespace ContainerC4jAqa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainOrUrlValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\Constraints\DomainOrUrlValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\DomainOrUrlValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/Constraints/DomainOrUrlValidator.php';

        return $container->privates['App\\Validator\\Constraints\\DomainOrUrlValidator'] = new \App\Validator\Constraints\DomainOrUrlValidator();
    }
}
