<?php

namespace ContainerC4jAqa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonitoringReportCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MonitoringReportCommand' shared autowired service.
     *
     * @return \App\Command\MonitoringReportCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/MonitoringReportCommand.php';

        $container->privates['App\\Command\\MonitoringReportCommand'] = $instance = new \App\Command\MonitoringReportCommand(($container->privates['App\\Service\\MonitoringService'] ?? $container->load('getMonitoringServiceService')));

        $instance->setName('app:monitoring:report');
        $instance->setDescription('Generate monitoring and performance report');

        return $instance;
    }
}
