<?php

namespace ContainerC4jAqa1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonitoringReportCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\MonitoringReportCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\MonitoringReportCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:monitoring:report', [], 'Generate monitoring and performance report', false, #[\Closure(name: 'App\\Command\\MonitoringReportCommand')] fn (): \App\Command\MonitoringReportCommand => ($container->privates['App\\Command\\MonitoringReportCommand'] ?? $container->load('getMonitoringReportCommandService')));
    }
}
