<?php

namespace ContainerWMXPbih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaseStudyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CaseStudyRepository' shared autowired service.
     *
     * @return \App\Repository\CaseStudyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CaseStudyRepository'] = new \App\Repository\CaseStudyRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
