<?php

namespace ContainerWMXPbih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTenantRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TenantRepository' shared autowired service.
     *
     * @return \App\Repository\TenantRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TenantRepository'] = new \App\Repository\TenantRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
