<?php

namespace ContainerTjJwj9j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditFindingsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\AuditFindingsController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\AuditFindingsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\AuditFindingsController'] = $instance = new \App\Controller\Api\V1\AuditFindingsController(($container->privates['App\\Repository\\AuditFindingRepository'] ?? $container->load('getAuditFindingRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\AuditFindingsController', $container));

        return $instance;
    }
}
