<?php

namespace ContainerTjJwj9j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentItemRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContentItemRepository' shared autowired service.
     *
     * @return \App\Repository\ContentItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContentItemRepository'] = new \App\Repository\ContentItemRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
