<?php

namespace ContainerTjJwj9j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrganizationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\OrganizationRepository' shared autowired service.
     *
     * @return \App\Repository\OrganizationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\OrganizationRepository'] = new \App\Repository\OrganizationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
