<?php

namespace ContainerRXVGlzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Symfony_UriVariables_Transformer_UlidService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.symfony.uri_variables.transformer.ulid' shared service.
     *
     * @return \ApiPlatform\Symfony\UriVariableTransformer\UlidUriVariableTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/UriVariableTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/symfony/UriVariableTransformer/UlidUriVariableTransformer.php';

        return $container->privates['api_platform.symfony.uri_variables.transformer.ulid'] = new \ApiPlatform\Symfony\UriVariableTransformer\UlidUriVariableTransformer();
    }
}
