<?php

namespace ContainerRXVGlzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityBacklinkApiPlatformDoctrineOrmFilterOrderFilterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'annotated_app_entity_backlink_api_platform_doctrine_orm_filter_order_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\OrderFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/PropertyAwareFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/ManagerRegistryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/OrderFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/JsonSchemaFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/OpenApiParameterFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/OrderFilterTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/PropertyPlaceholderOpenApiParameterTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/OrderFilter.php';

        return $container->privates['annotated_app_entity_backlink_api_platform_doctrine_orm_filter_order_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\OrderFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), 'order', ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['createdAt' => 'DESC', 'domainAuthority' => 'DESC', 'spamScore' => 'ASC'], ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)), NULL);
    }
}
