<?php

namespace ContainerRXVGlzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_StateProvider_Parameter_IriConverterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.state_provider.parameter.iri_converter' shared service.
     *
     * @return \ApiPlatform\State\ParameterProvider\IriConverterParameterProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ParameterProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/state/ParameterProvider/IriConverterParameterProvider.php';

        return $container->privates['api_platform.state_provider.parameter.iri_converter'] = new \ApiPlatform\State\ParameterProvider\IriConverterParameterProvider(($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container)));
    }
}
