<?php

namespace ContainerRXVGlzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityReviewApiPlatformDoctrineOrmFilterSearchFilterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'annotated_app_entity_review_api_platform_doctrine_orm_filter_search_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\SearchFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/metadata/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/PropertyAwareFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/ManagerRegistryAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/SearchFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-common/Filter/SearchFilterTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Filter/SearchFilter.php';

        $a = ($container->privates['api_platform.symfony.iri_converter'] ?? self::getApiPlatform_Symfony_IriConverterService($container));

        if (isset($container->privates['annotated_app_entity_review_api_platform_doctrine_orm_filter_search_filter'])) {
            return $container->privates['annotated_app_entity_review_api_platform_doctrine_orm_filter_search_filter'];
        }
        $b = ($container->privates['api_platform.api.identifiers_extractor'] ?? self::getApiPlatform_Api_IdentifiersExtractorService($container));

        if (isset($container->privates['annotated_app_entity_review_api_platform_doctrine_orm_filter_search_filter'])) {
            return $container->privates['annotated_app_entity_review_api_platform_doctrine_orm_filter_search_filter'];
        }

        return $container->privates['annotated_app_entity_review_api_platform_doctrine_orm_filter_search_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\SearchFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), $a, ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['clientId' => 'exact', 'platform' => 'exact', 'status' => 'exact', 'reviewerName' => 'partial'], $b, ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)));
    }
}
