<?php

namespace ContainerRXVGlzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSystemAccountCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateSystemAccountCommand' shared autowired service.
     *
     * @return \App\Command\CreateSystemAccountCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateSystemAccountCommand.php';

        $container->privates['App\\Command\\CreateSystemAccountCommand'] = $instance = new \App\Command\CreateSystemAccountCommand(($container->privates['App\\Service\\SystemAccountService'] ?? $container->load('getSystemAccountServiceService')));

        $instance->setName('app:create-system-account');
        $instance->setDescription('Create a new system account for backend operations');

        return $instance;
    }
}
