<?php

namespace ContainerRXVGlzE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagesControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\V1\PagesController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\PagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/V1/PagesController.php';

        $container->services['App\\Controller\\Api\\V1\\PagesController'] = $instance = new \App\Controller\Api\V1\PagesController(($container->privates['App\\Repository\\PageRepository'] ?? $container->load('getPageRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\PagesController', $container));

        return $instance;
    }
}
