<?php

namespace ContainerXmKRJIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatePackageCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CreatePackageCommand' shared autowired service.
     *
     * @return \App\Command\CreatePackageCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreatePackageCommand'] = $instance = new \App\Command\CreatePackageCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:create-package');
        $instance->setDescription('Create a new pricing package');

        return $instance;
    }
}
