<?php

namespace ContainerXmKRJIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadSourceRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LeadSourceRepository' shared autowired service.
     *
     * @return \App\Repository\LeadSourceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LeadSourceRepository'] = new \App\Repository\LeadSourceRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
