<?php

namespace ContainerXmKRJIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RecommendationRepository' shared autowired service.
     *
     * @return \App\Repository\RecommendationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RecommendationRepository'] = new \App\Repository\RecommendationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
