<?php

namespace ContainerXmKRJIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\TwilioService' shared autowired service.
     *
     * @return \App\Service\TwilioService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\TwilioService'] = new \App\Service\TwilioService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN'), $container->getEnv('TWILIO_PHONE_NUMBER'));
    }
}
