<?php

namespace ContainerXmKRJIr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestTwilioCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\TestTwilioCommand' shared autowired service.
     *
     * @return \App\Command\TestTwilioCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestTwilioCommand'] = $instance = new \App\Command\TestTwilioCommand(($container->privates['App\\Service\\TwilioService'] ?? $container->load('getTwilioServiceService')));

        $instance->setName('app:test-twilio');
        $instance->setDescription('Test Twilio integration by making a call to 786-213-3333');

        return $instance;
    }
}
