<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC4jAqa1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC4jAqa1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC4jAqa1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC4jAqa1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC4jAqa1\App_KernelDevDebugContainer([
    'container.build_hash' => 'C4jAqa1',
    'container.build_id' => '9b139c51',
    'container.build_time' => 1757441256,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC4jAqa1');
