<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTiciHRY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTiciHRY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTiciHRY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTiciHRY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTiciHRY\App_KernelDevDebugContainer([
    'container.build_hash' => 'TiciHRY',
    'container.build_id' => '6daf1bfb',
    'container.build_time' => 1755087881,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTiciHRY');
