<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKsXZ7dm\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKsXZ7dm/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerKsXZ7dm.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerKsXZ7dm\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerKsXZ7dm\App_KernelDevContainer([
    'container.build_hash' => 'KsXZ7dm',
    'container.build_id' => 'bdeffb57',
    'container.build_time' => 1757606586,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKsXZ7dm');
