<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250816000131 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Create organizations table first
        $this->addSql('CREATE TABLE organizations (id UUID NOT NULL, name VARCHAR(255) NOT NULL, domain VARCHAR(255) DEFAULT NULL, metadata JSONB DEFAULT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN organizations.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN organizations.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN organizations.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN organizations.updated_at IS \'(DC2Type:datetime_immutable)\'');

        // Create a default organization and update existing users
        $this->addSql('INSERT INTO organizations (id, name, domain, status, created_at, updated_at) VALUES (\'00000000-0000-0000-0000-000000000001\', \'Default Organization\', \'example.com\', \'active\', NOW(), NOW())');
        
        // Add organization_id column to users table
        $this->addSql('ALTER TABLE users ADD COLUMN organization_id UUID DEFAULT NULL');
        $this->addSql('UPDATE users SET organization_id = \'00000000-0000-0000-0000-000000000001\' WHERE organization_id IS NULL');
        $this->addSql('ALTER TABLE users ALTER COLUMN organization_id SET NOT NULL');

        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_findings (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, audit_run_id UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, severity VARCHAR(20) NOT NULL, status VARCHAR(50) NOT NULL, category VARCHAR(255) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, impact TEXT DEFAULT NULL, recommendation TEXT DEFAULT NULL, code_example TEXT DEFAULT NULL, score NUMERIC(5, 2) DEFAULT NULL, evidence JSONB DEFAULT NULL, "references" JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN audit_findings.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.audit_run_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.evidence IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings."references" IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN audit_findings.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE audit_runs (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, target_url VARCHAR(255) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, total_issues INT DEFAULT NULL, critical_issues INT DEFAULT NULL, high_issues INT DEFAULT NULL, medium_issues INT DEFAULT NULL, low_issues INT DEFAULT NULL, score NUMERIC(5, 2) DEFAULT NULL, settings JSONB DEFAULT NULL, results JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN audit_runs.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.settings IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.results IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN audit_runs.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE backlinks (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, source_url VARCHAR(500) NOT NULL, target_url VARCHAR(500) NOT NULL, anchor_text VARCHAR(255) DEFAULT NULL, source_domain VARCHAR(255) DEFAULT NULL, target_domain VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, link_type VARCHAR(20) NOT NULL, domain_authority INT DEFAULT NULL, spam_score INT DEFAULT NULL, page_authority INT DEFAULT NULL, country VARCHAR(50) DEFAULT NULL, language VARCHAR(50) DEFAULT NULL, first_seen TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_seen TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_social BOOLEAN DEFAULT false NOT NULL, is_news BOOLEAN DEFAULT false NOT NULL, is_blog BOOLEAN DEFAULT false NOT NULL, context JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN backlinks.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.first_seen IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.last_seen IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.context IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN backlinks.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE campaigns (id UUID NOT NULL, client_id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, budget NUMERIC(10, 2) DEFAULT NULL, goals JSONB DEFAULT NULL, metrics JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E373747019EB6921 ON campaigns (client_id)');
        $this->addSql('COMMENT ON COLUMN campaigns.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.start_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.end_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.goals IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.metrics IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN campaigns.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE case_studies (id UUID NOT NULL, tenant_id UUID NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, summary TEXT DEFAULT NULL, metrics_json JSONB NOT NULL, hero_image VARCHAR(255) DEFAULT NULL, practice_area VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, sort INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6C0AEF349033212A ON case_studies (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_case_studies_tenant_slug ON case_studies (tenant_id, slug)');
        $this->addSql('COMMENT ON COLUMN case_studies.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN case_studies.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN case_studies.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN case_studies.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE citations (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, platform VARCHAR(100) NOT NULL, business_name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, claim_status VARCHAR(50) DEFAULT NULL, claim_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, business_hours JSONB DEFAULT NULL, categories JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN citations.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN citations.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN citations.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN citations.claim_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN citations.business_hours IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN citations.categories IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN citations.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN citations.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN citations.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE client_locations (id UUID NOT NULL, client_id UUID NOT NULL, label VARCHAR(255) NOT NULL, street VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, is_primary BOOLEAN DEFAULT false NOT NULL, metadata JSONB DEFAULT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FCC69AB519EB6921 ON client_locations (client_id)');
        $this->addSql('COMMENT ON COLUMN client_locations.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN client_locations.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN client_locations.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN client_locations.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN client_locations.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE clients (id UUID NOT NULL, organization_id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, website_url VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, industry VARCHAR(255) DEFAULT \'law\' NOT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, metadata JSONB DEFAULT NULL, google_business_profile JSONB DEFAULT NULL, google_search_console JSONB DEFAULT NULL, google_analytics JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82E74989D9B62 ON clients (slug)');
        $this->addSql('CREATE INDEX IDX_C82E7432C8A3DE ON clients (organization_id)');
        $this->addSql('COMMENT ON COLUMN clients.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN clients.organization_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN clients.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN clients.google_business_profile IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN clients.google_search_console IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN clients.google_analytics IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN clients.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN clients.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE content_briefs (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, content_item_id UUID DEFAULT NULL, assigned_to UUID DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, target_audience TEXT DEFAULT NULL, key_messages TEXT DEFAULT NULL, call_to_action TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(20) NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, estimated_word_count INT DEFAULT NULL, keywords JSONB DEFAULT NULL, "references" JSONB DEFAULT NULL, requirements JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN content_briefs.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.content_item_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.assigned_to IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.due_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.keywords IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs."references" IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.requirements IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN content_briefs.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE content_items (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, author_id UUID DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, excerpt TEXT DEFAULT NULL, content TEXT NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, meta_title VARCHAR(255) DEFAULT NULL, meta_description TEXT DEFAULT NULL, meta_keywords JSONB DEFAULT NULL, featured_image VARCHAR(255) DEFAULT NULL, tags JSONB DEFAULT NULL, categories JSONB DEFAULT NULL, word_count INT DEFAULT 0 NOT NULL, read_time INT DEFAULT 0 NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, seo_settings JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ADDBD9F989D9B62 ON content_items (slug)');
        $this->addSql('COMMENT ON COLUMN content_items.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_items.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_items.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_items.author_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN content_items.meta_keywords IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_items.tags IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_items.categories IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_items.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN content_items.seo_settings IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_items.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN content_items.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN content_items.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE faqs (id UUID NOT NULL, question TEXT NOT NULL, answer_md TEXT NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, order_index INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN faqs.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN faqs.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN faqs.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE invoices (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, subscription_id UUID DEFAULT NULL, invoice_number VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, amount NUMERIC(10, 2) NOT NULL, tax_amount NUMERIC(10, 2) DEFAULT \'0\' NOT NULL, total_amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, issued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stripe_invoice_id VARCHAR(255) DEFAULT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, line_items JSONB DEFAULT NULL, tax_details JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN invoices.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoices.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoices.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoices.subscription_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN invoices.issued_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoices.due_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoices.paid_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoices.line_items IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN invoices.tax_details IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN invoices.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN invoices.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoices.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE keywords (id UUID NOT NULL, client_id UUID NOT NULL, phrase VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, difficulty VARCHAR(20) NOT NULL, search_volume INT DEFAULT NULL, cpc NUMERIC(5, 2) DEFAULT NULL, intent VARCHAR(50) DEFAULT NULL, related_keywords JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, locale VARCHAR(255) DEFAULT \'en-US\' NOT NULL, location VARCHAR(255) DEFAULT NULL, target_url VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AA5FB55E19EB6921 ON keywords (client_id)');
        $this->addSql('COMMENT ON COLUMN keywords.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN keywords.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN keywords.related_keywords IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN keywords.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN keywords.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN keywords.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE lead_events (id UUID NOT NULL, lead_id UUID NOT NULL, created_by_id UUID DEFAULT NULL, event_type VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, payload_json JSONB NOT NULL, severity VARCHAR(255) DEFAULT \'info\' NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2EE62E3655458D ON lead_events (lead_id)');
        $this->addSql('CREATE INDEX IDX_2EE62E36B03A8386 ON lead_events (created_by_id)');
        $this->addSql('COMMENT ON COLUMN lead_events.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.lead_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.created_by_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.payload_json IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.scheduled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lead_events.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE lead_sources (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, metadata JSONB DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B93399C5E237E06 ON lead_sources (name)');
        $this->addSql('COMMENT ON COLUMN lead_sources.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN lead_sources.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN lead_sources.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN lead_sources.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE leads (id UUID NOT NULL, client_id UUID DEFAULT NULL, source_id UUID DEFAULT NULL, full_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, firm VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, practice_areas TEXT DEFAULT \'{}\' NOT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(255) DEFAULT NULL, message TEXT DEFAULT NULL, status VARCHAR(16) DEFAULT \'new\' NOT NULL, utm_json JSON DEFAULT \'{}\' NOT NULL, is_test BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1790455219EB6921 ON leads (client_id)');
        $this->addSql('CREATE INDEX IDX_17904552953C1C61 ON leads (source_id)');
        $this->addSql('COMMENT ON COLUMN leads.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN leads.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN leads.source_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN leads.practice_areas IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN leads.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN leads.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE media_assets (id UUID NOT NULL, owner_client_id UUID DEFAULT NULL, filename VARCHAR(255) NOT NULL, original_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size BIGINT NOT NULL, storage_key VARCHAR(255) NOT NULL, storage_provider VARCHAR(50) NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, alt_text VARCHAR(255) DEFAULT NULL, type VARCHAR(50) NOT NULL, dimensions JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, processing_status JSONB DEFAULT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C5A8E7501B901A92 ON media_assets (owner_client_id)');
        $this->addSql('COMMENT ON COLUMN media_assets.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.owner_client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.dimensions IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.processing_status IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.uploaded_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN media_assets.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE newsletter_subscriptions (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, email VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, company VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, interests JSONB DEFAULT NULL, status VARCHAR(255) DEFAULT \'subscribed\' NOT NULL, source VARCHAR(255) DEFAULT NULL, metadata JSONB DEFAULT NULL, subscribed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, unsubscribed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.interests IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.subscribed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.unsubscribed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN newsletter_subscriptions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE oauth_connections (id UUID NOT NULL, client_id UUID NOT NULL, provider VARCHAR(255) NOT NULL, external_account_id VARCHAR(255) DEFAULT NULL, scopes JSONB NOT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E3D750BE19EB6921 ON oauth_connections (client_id)');
        $this->addSql('COMMENT ON COLUMN oauth_connections.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN oauth_connections.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN oauth_connections.scopes IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN oauth_connections.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN oauth_connections.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN oauth_connections.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE oauth_tokens (id UUID NOT NULL, connection_id UUID NOT NULL, access_token TEXT NOT NULL, refresh_token TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C06D3296DD03F01 ON oauth_tokens (connection_id)');
        $this->addSql('COMMENT ON COLUMN oauth_tokens.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN oauth_tokens.connection_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN oauth_tokens.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN oauth_tokens.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN oauth_tokens.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN oauth_tokens.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE packages (id UUID NOT NULL, client_id UUID DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, billing_cycle VARCHAR(50) DEFAULT NULL, features JSONB NOT NULL, included_services JSONB NOT NULL, is_popular BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, sort_order INT DEFAULT 0 NOT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN packages.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN packages.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN packages.features IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN packages.included_services IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN packages.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN packages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN packages.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rankings (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, keyword_id UUID NOT NULL, date DATE NOT NULL, search_engine VARCHAR(50) NOT NULL, location VARCHAR(100) DEFAULT NULL, device VARCHAR(50) DEFAULT NULL, position INT NOT NULL, url VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, snippet TEXT DEFAULT NULL, features JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN rankings.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rankings.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rankings.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rankings.keyword_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rankings.features IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN rankings.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN rankings.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN rankings.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE rankings_daily (id UUID NOT NULL, keyword_id UUID NOT NULL, date DATE NOT NULL, serp_position INT DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, impressions INT DEFAULT NULL, clicks INT DEFAULT NULL, ctr DOUBLE PRECISION DEFAULT NULL, avg_position DOUBLE PRECISION DEFAULT NULL, serp_features JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B0D35353115D4552 ON rankings_daily (keyword_id)');
        $this->addSql('COMMENT ON COLUMN rankings_daily.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rankings_daily.keyword_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN rankings_daily.serp_features IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN rankings_daily.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN rankings_daily.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN rankings_daily.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE recommendations (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, category VARCHAR(50) NOT NULL, priority VARCHAR(20) NOT NULL, status VARCHAR(50) NOT NULL, rationale TEXT DEFAULT NULL, implementation TEXT DEFAULT NULL, expected_outcome TEXT DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assigned_to UUID DEFAULT NULL, estimated_effort NUMERIC(5, 2) DEFAULT NULL, estimated_cost NUMERIC(5, 2) DEFAULT NULL, tags JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN recommendations.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.due_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.assigned_to IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.tags IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN recommendations.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE reviews (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, platform VARCHAR(100) NOT NULL, review_id VARCHAR(255) DEFAULT NULL, reviewer_name VARCHAR(255) NOT NULL, rating INT NOT NULL, title TEXT DEFAULT NULL, content TEXT NOT NULL, status VARCHAR(50) NOT NULL, review_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reviewer_image VARCHAR(255) DEFAULT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, is_response BOOLEAN DEFAULT false NOT NULL, response TEXT DEFAULT NULL, response_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN reviews.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reviews.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reviews.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN reviews.review_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reviews.response_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reviews.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN reviews.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reviews.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE subscriptions (id UUID NOT NULL, tenant_id UUID DEFAULT NULL, client_id UUID NOT NULL, package_id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, amount NUMERIC(10, 2) NOT NULL, currency VARCHAR(3) NOT NULL, billing_cycle VARCHAR(20) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, next_billing_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, stripe_customer_id VARCHAR(255) DEFAULT NULL, quantity INT DEFAULT 1 NOT NULL, auto_renew BOOLEAN DEFAULT false NOT NULL, notes TEXT DEFAULT NULL, features JSONB DEFAULT NULL, metadata JSONB DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN subscriptions.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.package_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.start_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.next_billing_date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.cancelled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.features IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN subscriptions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE system_users (id UUID NOT NULL, username VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, permissions JSON NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_404C3E73F85E0677 ON system_users (username)');
        $this->addSql('COMMENT ON COLUMN system_users.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN system_users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN system_users.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE user_client_access (id UUID NOT NULL, user_id UUID NOT NULL, client_id UUID NOT NULL, permissions JSONB DEFAULT NULL, status VARCHAR(255) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BD41CDB7A76ED395 ON user_client_access (user_id)');
        $this->addSql('CREATE INDEX IDX_BD41CDB719EB6921 ON user_client_access (client_id)');
        $this->addSql('COMMENT ON COLUMN user_client_access.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_client_access.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_client_access.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN user_client_access.permissions IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN user_client_access.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_client_access.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE campaigns ADD CONSTRAINT FK_E373747019EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE case_studies ADD CONSTRAINT FK_6C0AEF349033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client_locations ADD CONSTRAINT FK_FCC69AB519EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE clients ADD CONSTRAINT FK_C82E7432C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE keywords ADD CONSTRAINT FK_AA5FB55E19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lead_events ADD CONSTRAINT FK_2EE62E3655458D FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lead_events ADD CONSTRAINT FK_2EE62E36B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_1790455219EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE leads ADD CONSTRAINT FK_17904552953C1C61 FOREIGN KEY (source_id) REFERENCES lead_sources (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media_assets ADD CONSTRAINT FK_C5A8E7501B901A92 FOREIGN KEY (owner_client_id) REFERENCES clients (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE oauth_connections ADD CONSTRAINT FK_E3D750BE19EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE oauth_tokens ADD CONSTRAINT FK_C06D3296DD03F01 FOREIGN KEY (connection_id) REFERENCES oauth_connections (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rankings_daily ADD CONSTRAINT FK_B0D35353115D4552 FOREIGN KEY (keyword_id) REFERENCES keywords (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_client_access ADD CONSTRAINT FK_BD41CDB7A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_client_access ADD CONSTRAINT FK_BD41CDB719EB6921 FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF346689033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_3AF346689033212A ON categories (tenant_id)');
        $this->addSql('DROP INDEX uniq_2074e5759033212af6bd1646989d9b62');
        $this->addSql('ALTER TABLE pages ADD client_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD excerpt TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD meta_title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD meta_description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD meta_keywords JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD featured_image VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD type VARCHAR(50) DEFAULT \'page\' NOT NULL');
        $this->addSql('ALTER TABLE pages ADD sort_order INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE pages ADD metadata JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE pages ADD seo_settings JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE pages DROP tenant_id');
        $this->addSql('ALTER TABLE pages DROP site_id');
        $this->addSql('ALTER TABLE pages ALTER content SET NOT NULL');
        $this->addSql('ALTER TABLE pages ALTER status SET DEFAULT \'published\'');
        $this->addSql('ALTER TABLE pages ALTER published_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('COMMENT ON COLUMN pages.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pages.meta_keywords IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN pages.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN pages.seo_settings IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN pages.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN pages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN pages.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2074E575989D9B62 ON pages (slug)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFA9033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_885DBAFA9033212A ON posts (tenant_id)');
        $this->addSql('ALTER TABLE tags ADD CONSTRAINT FK_6FBC94269033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_6FBC94269033212A ON tags (tenant_id)');
        $this->addSql('DROP INDEX uniq_1483a5e99033212ae7927c74');
        // organization_id column already added above
        $this->addSql('ALTER TABLE users ADD client_id UUID DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD last_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD role VARCHAR(32) DEFAULT \'ROLE_USER\'');
        $this->addSql('UPDATE users SET role = \'ROLE_USER\' WHERE role IS NULL');
        $this->addSql('ALTER TABLE users ALTER COLUMN role SET NOT NULL');
        $this->addSql('ALTER TABLE users ADD metadata JSONB DEFAULT NULL');
        $this->addSql('ALTER TABLE users DROP roles');
        $this->addSql('ALTER TABLE users ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users RENAME COLUMN name TO first_name');
        $this->addSql('COMMENT ON COLUMN users.organization_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.client_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.metadata IS \'(DC2Type:jsonb)\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E932C8A3DE FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E99033212A FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_1483A5E932C8A3DE ON users (organization_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E99033212A ON users (tenant_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E932C8A3DE');
        $this->addSql('ALTER TABLE campaigns DROP CONSTRAINT FK_E373747019EB6921');
        $this->addSql('ALTER TABLE case_studies DROP CONSTRAINT FK_6C0AEF349033212A');
        $this->addSql('ALTER TABLE client_locations DROP CONSTRAINT FK_FCC69AB519EB6921');
        $this->addSql('ALTER TABLE clients DROP CONSTRAINT FK_C82E7432C8A3DE');
        $this->addSql('ALTER TABLE keywords DROP CONSTRAINT FK_AA5FB55E19EB6921');
        $this->addSql('ALTER TABLE lead_events DROP CONSTRAINT FK_2EE62E3655458D');
        $this->addSql('ALTER TABLE lead_events DROP CONSTRAINT FK_2EE62E36B03A8386');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_1790455219EB6921');
        $this->addSql('ALTER TABLE leads DROP CONSTRAINT FK_17904552953C1C61');
        $this->addSql('ALTER TABLE media_assets DROP CONSTRAINT FK_C5A8E7501B901A92');
        $this->addSql('ALTER TABLE oauth_connections DROP CONSTRAINT FK_E3D750BE19EB6921');
        $this->addSql('ALTER TABLE oauth_tokens DROP CONSTRAINT FK_C06D3296DD03F01');
        $this->addSql('ALTER TABLE rankings_daily DROP CONSTRAINT FK_B0D35353115D4552');
        $this->addSql('ALTER TABLE user_client_access DROP CONSTRAINT FK_BD41CDB7A76ED395');
        $this->addSql('ALTER TABLE user_client_access DROP CONSTRAINT FK_BD41CDB719EB6921');
        $this->addSql('DROP TABLE audit_findings');
        $this->addSql('DROP TABLE audit_runs');
        $this->addSql('DROP TABLE backlinks');
        $this->addSql('DROP TABLE campaigns');
        $this->addSql('DROP TABLE case_studies');
        $this->addSql('DROP TABLE citations');
        $this->addSql('DROP TABLE client_locations');
        $this->addSql('DROP TABLE clients');
        $this->addSql('DROP TABLE content_briefs');
        $this->addSql('DROP TABLE content_items');
        $this->addSql('DROP TABLE faqs');
        $this->addSql('DROP TABLE invoices');
        $this->addSql('DROP TABLE keywords');
        $this->addSql('DROP TABLE lead_events');
        $this->addSql('DROP TABLE lead_sources');
        $this->addSql('DROP TABLE leads');
        $this->addSql('DROP TABLE media_assets');
        $this->addSql('DROP TABLE newsletter_subscriptions');
        $this->addSql('DROP TABLE oauth_connections');
        $this->addSql('DROP TABLE oauth_tokens');
        $this->addSql('DROP TABLE organizations');
        $this->addSql('DROP TABLE packages');
        $this->addSql('DROP TABLE rankings');
        $this->addSql('DROP TABLE rankings_daily');
        $this->addSql('DROP TABLE recommendations');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE subscriptions');
        $this->addSql('DROP TABLE system_users');
        $this->addSql('DROP TABLE user_client_access');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF346689033212A');
        $this->addSql('DROP INDEX IDX_3AF346689033212A');
        $this->addSql('ALTER TABLE posts DROP CONSTRAINT FK_885DBAFA9033212A');
        $this->addSql('DROP INDEX IDX_885DBAFA9033212A');
        $this->addSql('ALTER TABLE tags DROP CONSTRAINT FK_6FBC94269033212A');
        $this->addSql('DROP INDEX IDX_6FBC94269033212A');
        $this->addSql('DROP INDEX UNIQ_2074E575989D9B62');
        $this->addSql('ALTER TABLE pages ADD tenant_id UUID NOT NULL');
        $this->addSql('ALTER TABLE pages ADD site_id UUID NOT NULL');
        $this->addSql('ALTER TABLE pages DROP client_id');
        $this->addSql('ALTER TABLE pages DROP excerpt');
        $this->addSql('ALTER TABLE pages DROP meta_title');
        $this->addSql('ALTER TABLE pages DROP meta_description');
        $this->addSql('ALTER TABLE pages DROP meta_keywords');
        $this->addSql('ALTER TABLE pages DROP featured_image');
        $this->addSql('ALTER TABLE pages DROP type');
        $this->addSql('ALTER TABLE pages DROP sort_order');
        $this->addSql('ALTER TABLE pages DROP metadata');
        $this->addSql('ALTER TABLE pages DROP seo_settings');
        $this->addSql('ALTER TABLE pages ALTER content DROP NOT NULL');
        $this->addSql('ALTER TABLE pages ALTER status SET DEFAULT \'draft\'');
        $this->addSql('ALTER TABLE pages ALTER published_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('COMMENT ON COLUMN pages.tenant_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pages.site_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN pages.published_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN pages.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN pages.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_2074e5759033212af6bd1646989d9b62 ON pages (tenant_id, site_id, slug)');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E99033212A');
        $this->addSql('DROP INDEX IDX_1483A5E932C8A3DE');
        $this->addSql('DROP INDEX IDX_1483A5E99033212A');
        $this->addSql('ALTER TABLE users ADD name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD roles JSON NOT NULL');
        $this->addSql('ALTER TABLE users DROP organization_id');
        $this->addSql('ALTER TABLE users DROP client_id');
        $this->addSql('ALTER TABLE users DROP first_name');
        $this->addSql('ALTER TABLE users DROP last_name');
        $this->addSql('ALTER TABLE users DROP role');
        $this->addSql('ALTER TABLE users DROP metadata');
        $this->addSql('ALTER TABLE users ALTER created_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER updated_at TYPE TIMESTAMP(0) WITH TIME ZONE');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetimetz_immutable)\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_1483a5e99033212ae7927c74 ON users (tenant_id, email)');
    }
}
