<?php

namespace ContainerURiSCUB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCitationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CitationRepository' shared autowired service.
     *
     * @return \App\Repository\CitationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CitationRepository'] = new \App\Repository\CitationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
