<?php

namespace ContainerURiSCUB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoicesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\InvoicesController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\InvoicesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\InvoicesController'] = $instance = new \App\Controller\Api\V1\InvoicesController(($container->privates['App\\Repository\\InvoiceRepository'] ?? $container->load('getInvoiceRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\InvoicesController', $container));

        return $instance;
    }
}
