<?php

namespace ContainerURiSCUB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubscriptionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SubscriptionRepository' shared autowired service.
     *
     * @return \App\Repository\SubscriptionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SubscriptionRepository'] = new \App\Repository\SubscriptionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
