<?php

namespace ContainerDojRjxV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateClientCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\CreateClientCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\CreateClientCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-client', [], 'Create a new client (law firm)', false, #[\Closure(name: 'App\\Command\\CreateClientCommand')] fn (): \App\Command\CreateClientCommand => ($container->privates['App\\Command\\CreateClientCommand'] ?? $container->load('getCreateClientCommandService')));
    }
}
