<?php

namespace ContainerDojRjxV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSystemAccountCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateSystemAccountCommand' shared autowired service.
     *
     * @return \App\Command\CreateSystemAccountCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateSystemAccountCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/SystemAccountService.php';

        $container->privates['App\\Command\\CreateSystemAccountCommand'] = $instance = new \App\Command\CreateSystemAccountCommand(new \App\Service\SystemAccountService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'))));

        $instance->setName('app:create-system-account');
        $instance->setDescription('Create a new system account for backend operations');

        return $instance;
    }
}
