<?php

namespace ContainerDojRjxV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTenantExtensionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\ApiPlatform\TenantExtension' shared autowired service.
     *
     * @return \App\ApiPlatform\TenantExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Extension/QueryCollectionExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/doctrine-orm/Extension/QueryItemExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/src/ApiPlatform/TenantExtension.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\ApiPlatform\\TenantExtension'])) {
            return $container->privates['App\\ApiPlatform\\TenantExtension'];
        }

        return $container->privates['App\\ApiPlatform\\TenantExtension'] = new \App\ApiPlatform\TenantExtension($a);
    }
}
