<?php

namespace Container1x874Aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditFindingRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AuditFindingRepository' shared autowired service.
     *
     * @return \App\Repository\AuditFindingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AuditFindingRepository'] = new \App\Repository\AuditFindingRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
