<?php

namespace Container1x874Aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSystemAccountCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\CreateSystemAccountCommand' shared autowired service.
     *
     * @return \App\Command\CreateSystemAccountCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\CreateSystemAccountCommand'] = $instance = new \App\Command\CreateSystemAccountCommand(new \App\Service\SystemAccountService(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'))));

        $instance->setName('app:create-system-account');
        $instance->setDescription('Create a new system account for backend operations');

        return $instance;
    }
}
