<?php

namespace Container1x874Aq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaAssetRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\MediaAssetRepository' shared autowired service.
     *
     * @return \App\Repository\MediaAssetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\MediaAssetRepository'] = new \App\Repository\MediaAssetRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
