<?php

namespace ContainerIiL349Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainOrUrlValidatorService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Validator\Constraints\DomainOrUrlValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\DomainOrUrlValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Validator\\Constraints\\DomainOrUrlValidator'] = new \App\Validator\Constraints\DomainOrUrlValidator();
    }
}
