<?php

namespace ContainerIiL349Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewsControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\ReviewsController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\ReviewsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\ReviewsController'] = $instance = new \App\Controller\Api\V1\ReviewsController(($container->privates['App\\Repository\\ReviewRepository'] ?? $container->load('getReviewRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\ReviewsController', $container));

        return $instance;
    }
}
