<?php

namespace ContainerKsXZ7dm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonitoringServiceService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Service\MonitoringService' shared autowired service.
     *
     * @return \App\Service\MonitoringService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\MonitoringService'] = new \App\Service\MonitoringService(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)), ($container->services['cache.app'] ?? $container->load('getCache_AppService')));
    }
}
