<?php

namespace Container4qBStD5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityKeywordApiPlatformDoctrineOrmFilterDateFilterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'annotated_app_entity_keyword_api_platform_doctrine_orm_filter_date_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\DateFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['annotated_app_entity_keyword_api_platform_doctrine_orm_filter_date_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\DateFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['createdAt' => NULL, 'updatedAt' => NULL], ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)));
    }
}
