<?php

namespace Container4qBStD5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuilderRegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Endroid\QrCode\Builder\BuilderRegistry' shared autowired service.
     *
     * @return \Endroid\QrCode\Builder\BuilderRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Endroid\\QrCode\\Builder\\BuilderRegistry'] = $instance = new \Endroid\QrCode\Builder\BuilderRegistry();

        $instance->set('default', new \Endroid\QrCode\Builder\Builder(new \Endroid\QrCode\Writer\PngWriter(), [], false, '', new \Endroid\QrCode\Encoding\Encoding('UTF-8'), \Endroid\QrCode\ErrorCorrectionLevel::Low, 300, 10, \Endroid\QrCode\RoundBlockSizeMode::Margin));

        return $instance;
    }
}
