<?php

namespace Container4qBStD5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CampaignRepository' shared autowired service.
     *
     * @return \App\Repository\CampaignRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CampaignRepository'] = new \App\Repository\CampaignRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
