<?php

namespace Container4qBStD5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyTulsaLeadsCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\VerifyTulsaLeadsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\VerifyTulsaLeadsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:verify-tulsa-leads', [], 'Verify Tulsa attorneys leads are properly imported', false, #[\Closure(name: 'App\\Command\\VerifyTulsaLeadsCommand')] fn (): \App\Command\VerifyTulsaLeadsCommand => ($container->privates['App\\Command\\VerifyTulsaLeadsCommand'] ?? $container->load('getVerifyTulsaLeadsCommandService')));
    }
}
