global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Audit Service PHP-FPM
  - job_name: 'audit-service-php'
    static_configs:
      - targets: ['php:9000']
    metrics_path: /status
    scrape_interval: 30s

  # Nginx
  - job_name: 'audit-service-nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'audit-service-postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'audit-service-redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # MinIO
  - job_name: 'audit-service-minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster
    scrape_interval: 30s

  # Chrome Headless
  - job_name: 'audit-service-chrome'
    static_configs:
      - targets: ['chrome:9222']
    scrape_interval: 30s

  # Jaeger
  - job_name: 'audit-service-jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    scrape_interval: 30s

  # Custom metrics endpoint
  - job_name: 'audit-service-metrics'
    static_configs:
      - targets: ['php:8080']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
