<?php

namespace ContainerA4seVtK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityRankingApiPlatformDoctrineOrmFilterRangeFilterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'annotated_app_entity_ranking_api_platform_doctrine_orm_filter_range_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\RangeFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['annotated_app_entity_ranking_api_platform_doctrine_orm_filter_range_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\RangeFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['position' => NULL], ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)));
    }
}
