<?php

namespace ContainerA4seVtK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendationsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\RecommendationsController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\RecommendationsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\RecommendationsController'] = $instance = new \App\Controller\Api\V1\RecommendationsController(($container->privates['App\\Repository\\RecommendationRepository'] ?? $container->load('getRecommendationRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\RecommendationsController', $container));

        return $instance;
    }
}
