<?php

namespace ContainerBqDgESN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBacklinkRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\BacklinkRepository' shared autowired service.
     *
     * @return \App\Repository\BacklinkRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\BacklinkRepository'] = new \App\Repository\BacklinkRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
