<?php

namespace ContainerXYgVwW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuditIntakeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AuditIntakeRepository' shared autowired service.
     *
     * @return \App\Repository\AuditIntakeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AuditIntakeRepository'] = new \App\Repository\AuditIntakeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
