<?php

namespace ContainerXYgVwW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateSystemAccountCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CreateSystemAccountCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CreateSystemAccountCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-system-account', [], 'Create a new system account for backend operations', false, #[\Closure(name: 'App\\Command\\CreateSystemAccountCommand')] fn (): \App\Command\CreateSystemAccountCommand => ($container->privates['App\\Command\\CreateSystemAccountCommand'] ?? $container->load('getCreateSystemAccountCommandService')));
    }
}
