<?php

namespace ContainerXYgVwW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportRealTulsaAttorneysCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\ImportRealTulsaAttorneysCommand' shared autowired service.
     *
     * @return \App\Command\ImportRealTulsaAttorneysCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\ImportRealTulsaAttorneysCommand'] = $instance = new \App\Command\ImportRealTulsaAttorneysCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:import-real-tulsa-attorneys');
        $instance->setDescription('Imports real Tulsa attorneys lead data from Google Places API into the database.');

        return $instance;
    }
}
