<?php

namespace ContainerXYgVwW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncGoogleBusinessProfileDataCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\SyncGoogleBusinessProfileDataCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\SyncGoogleBusinessProfileDataCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:sync-gbp-data', [], 'Sync Google Business Profile data for all connected clients', false, #[\Closure(name: 'App\\Command\\SyncGoogleBusinessProfileDataCommand')] fn (): \App\Command\SyncGoogleBusinessProfileDataCommand => ($container->privates['App\\Command\\SyncGoogleBusinessProfileDataCommand'] ?? $container->load('getSyncGoogleBusinessProfileDataCommandService')));
    }
}
