<?php

namespace ContainerXYgVwW3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestTulsaLeadsAPICommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\TestTulsaLeadsAPICommand' shared autowired service.
     *
     * @return \App\Command\TestTulsaLeadsAPICommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestTulsaLeadsAPICommand'] = $instance = new \App\Command\TestTulsaLeadsAPICommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\LeadRepository'] ?? $container->load('getLeadRepositoryService')));

        $instance->setName('app:test-tulsa-leads-api');
        $instance->setDescription('Test Tulsa attorneys leads API response format');

        return $instance;
    }
}
