<?php

namespace Container53jxOc7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Api\\V1\\NotificationsController::show' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::show()', 'getNotificationsControllershowService', true],
            'App\\Controller\\Api\\V1\\NotificationsController::markAsRead' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::markAsRead()', 'getNotificationsControllermarkAsReadService', true],
            'App\\Controller\\Api\\V1\\NotificationsController::markAsUnread' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::markAsUnread()', 'getNotificationsControllermarkAsUnreadService', true],
            'App\\Controller\\Api\\V1\\NotificationsController::delete' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::delete()', 'getNotificationsControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Api\\V1\\NotificationsController:show' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::show()', 'getNotificationsControllershowService', true],
            'App\\Controller\\Api\\V1\\NotificationsController:markAsRead' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::markAsRead()', 'getNotificationsControllermarkAsReadService', true],
            'App\\Controller\\Api\\V1\\NotificationsController:markAsUnread' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::markAsUnread()', 'getNotificationsControllermarkAsUnreadService', true],
            'App\\Controller\\Api\\V1\\NotificationsController:delete' => ['privates', '.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::delete()', 'getNotificationsControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController::show' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController::markAsRead' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController::markAsUnread' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController:show' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController:markAsRead' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController:markAsUnread' => '?',
            'App\\Controller\\Api\\V1\\NotificationsController:delete' => '?',
        ]));
    }
}
