<?php

namespace Container53jxOc7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Doctrine_Orm_Extension_ParameterExtensionService extends App_KernelProdContainer
{
    /*
     * Gets the private 'api_platform.doctrine.orm.extension.parameter_extension' shared service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Extension\ParameterExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['api_platform.filter_locator'] ?? self::getApiPlatform_FilterLocatorService($container));

        if (isset($container->privates['api_platform.doctrine.orm.extension.parameter_extension'])) {
            return $container->privates['api_platform.doctrine.orm.extension.parameter_extension'];
        }

        return $container->privates['api_platform.doctrine.orm.extension.parameter_extension'] = new \ApiPlatform\Doctrine\Orm\Extension\ParameterExtension($a, ($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
