<?php

namespace Container53jxOc7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFaqRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FaqRepository' shared autowired service.
     *
     * @return \App\Repository\FaqRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FaqRepository'] = new \App\Repository\FaqRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
