<?php

namespace Container53jxOc7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationsControllermarkAsReadService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.KaYtR3O.App\Controller\Api\V1\NotificationsController::markAsRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KaYtR3O.App\\Controller\\Api\\V1\\NotificationsController::markAsRead()'] = ($container->privates['.service_locator.KaYtR3O'] ?? $container->load('get_ServiceLocator_KaYtR3OService'))->withContext('App\\Controller\\Api\\V1\\NotificationsController::markAsRead()', $container);
    }
}
