<?php

namespace Container53jxOc7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyRealTulsaLeadsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\VerifyRealTulsaLeadsCommand' shared autowired service.
     *
     * @return \App\Command\VerifyRealTulsaLeadsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\VerifyRealTulsaLeadsCommand'] = $instance = new \App\Command\VerifyRealTulsaLeadsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:verify-real-tulsa-leads');
        $instance->setDescription('Verifies that real Tulsa attorneys leads from Google Places API are in the database with "new_lead" status.');

        return $instance;
    }
}
