doctrine:
    dbal:
        url: '%env(DB_DSN)%'
        driver: 'pdo_pgsql'
        server_version: '16'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        types:
            jsonb: App\Doctrine\DBAL\Types\JsonbType
            uuid: Doctrine\DBAL\Types\UuidType
    
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        
        # Filters for multi-tenancy
        filters:
            tenant_filter:
                class: App\Doctrine\Filter\TenantFilter
                enabled: true
        
        # DQL functions
        dql:
            string_functions:
                json_extract: App\Doctrine\DQL\JsonExtractFunction
                json_extract_text: App\Doctrine\DQL\JsonExtractTextFunction
