<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocumentSignature extends \App\Entity\DocumentSignature implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'document' => [parent::class, 'document', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'ipAddress' => [parent::class, 'ipAddress', null, 16],
        "\0".parent::class."\0".'isDigitalSignature' => [parent::class, 'isDigitalSignature', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'signatureData' => [parent::class, 'signatureData', null, 16],
        "\0".parent::class."\0".'signatureImage' => [parent::class, 'signatureImage', null, 16],
        "\0".parent::class."\0".'signedAt' => [parent::class, 'signedAt', null, 16],
        "\0".parent::class."\0".'signedBy' => [parent::class, 'signedBy', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userAgent' => [parent::class, 'userAgent', null, 16],
        'comments' => [parent::class, 'comments', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'document' => [parent::class, 'document', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'ipAddress' => [parent::class, 'ipAddress', null, 16],
        'isDigitalSignature' => [parent::class, 'isDigitalSignature', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'signatureData' => [parent::class, 'signatureData', null, 16],
        'signatureImage' => [parent::class, 'signatureImage', null, 16],
        'signedAt' => [parent::class, 'signedAt', null, 16],
        'signedBy' => [parent::class, 'signedBy', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userAgent' => [parent::class, 'userAgent', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
