<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Citation extends \App\Entity\Citation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'businessHours' => [parent::class, 'businessHours', null, 16],
        "\0".parent::class."\0".'businessName' => [parent::class, 'businessName', null, 16],
        "\0".parent::class."\0".'categories' => [parent::class, 'categories', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'claimDate' => [parent::class, 'claimDate', null, 16],
        "\0".parent::class."\0".'claimStatus' => [parent::class, 'claimStatus', null, 16],
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'platform' => [parent::class, 'platform', null, 16],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tenantId' => [parent::class, 'tenantId', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'url' => [parent::class, 'url', null, 16],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null, 16],
        "\0".parent::class."\0".'zipCode' => [parent::class, 'zipCode', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'businessHours' => [parent::class, 'businessHours', null, 16],
        'businessName' => [parent::class, 'businessName', null, 16],
        'categories' => [parent::class, 'categories', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'claimDate' => [parent::class, 'claimDate', null, 16],
        'claimStatus' => [parent::class, 'claimStatus', null, 16],
        'clientId' => [parent::class, 'clientId', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'platform' => [parent::class, 'platform', null, 16],
        'state' => [parent::class, 'state', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tenantId' => [parent::class, 'tenantId', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'url' => [parent::class, 'url', null, 16],
        'website' => [parent::class, 'website', null, 16],
        'zipCode' => [parent::class, 'zipCode', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
