<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        'authorId' => [parent::class, 'authorId', null, 4],
        'createdAt' => [parent::class, 'createdAt', null, 4],
        'excerpt' => [parent::class, 'excerpt', null, 4],
        'id' => [parent::class, 'id', null, 16],
        'publishedAt' => [parent::class, 'publishedAt', null, 4],
        'siteId' => [parent::class, 'siteId', null, 4],
        'slug' => [parent::class, 'slug', null, 4],
        'status' => [parent::class, 'status', null, 4],
        'tenant' => [parent::class, 'tenant', null, 16],
        'title' => [parent::class, 'title', null, 4],
        'updatedAt' => [parent::class, 'updatedAt', null, 4],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
