<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recommendation extends \App\Entity\Recommendation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'assignedTo' => [parent::class, 'assignedTo', null, 16],
        "\0".parent::class."\0".'category' => [parent::class, 'category', null, 16],
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'completedAt' => [parent::class, 'completedAt', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'dueDate' => [parent::class, 'dueDate', null, 16],
        "\0".parent::class."\0".'estimatedCost' => [parent::class, 'estimatedCost', null, 16],
        "\0".parent::class."\0".'estimatedEffort' => [parent::class, 'estimatedEffort', null, 16],
        "\0".parent::class."\0".'expectedOutcome' => [parent::class, 'expectedOutcome', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'implementation' => [parent::class, 'implementation', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'priority' => [parent::class, 'priority', null, 16],
        "\0".parent::class."\0".'rationale' => [parent::class, 'rationale', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tags' => [parent::class, 'tags', null, 16],
        "\0".parent::class."\0".'tenantId' => [parent::class, 'tenantId', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'assignedTo' => [parent::class, 'assignedTo', null, 16],
        'category' => [parent::class, 'category', null, 16],
        'clientId' => [parent::class, 'clientId', null, 16],
        'completedAt' => [parent::class, 'completedAt', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'dueDate' => [parent::class, 'dueDate', null, 16],
        'estimatedCost' => [parent::class, 'estimatedCost', null, 16],
        'estimatedEffort' => [parent::class, 'estimatedEffort', null, 16],
        'expectedOutcome' => [parent::class, 'expectedOutcome', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'implementation' => [parent::class, 'implementation', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'priority' => [parent::class, 'priority', null, 16],
        'rationale' => [parent::class, 'rationale', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tags' => [parent::class, 'tags', null, 16],
        'tenantId' => [parent::class, 'tenantId', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
