<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AuditKeyword extends \App\Entity\AuditKeyword implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'intake' => [parent::class, 'intake', null, 16],
        "\0".parent::class."\0".'intent' => [parent::class, 'intent', null, 16],
        "\0".parent::class."\0".'phrase' => [parent::class, 'phrase', null, 16],
        "\0".parent::class."\0".'priority' => [parent::class, 'priority', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'intake' => [parent::class, 'intake', null, 16],
        'intent' => [parent::class, 'intent', null, 16],
        'phrase' => [parent::class, 'phrase', null, 16],
        'priority' => [parent::class, 'priority', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
