<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MediaAsset extends \App\Entity\MediaAsset implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'altText' => [parent::class, 'altText', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'dimensions' => [parent::class, 'dimensions', null, 16],
        "\0".parent::class."\0".'fileSize' => [parent::class, 'fileSize', null, 16],
        "\0".parent::class."\0".'filename' => [parent::class, 'filename', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'mimeType' => [parent::class, 'mimeType', null, 16],
        "\0".parent::class."\0".'originalFilename' => [parent::class, 'originalFilename', null, 16],
        "\0".parent::class."\0".'ownerClient' => [parent::class, 'ownerClient', null, 16],
        "\0".parent::class."\0".'processingStatus' => [parent::class, 'processingStatus', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'storageKey' => [parent::class, 'storageKey', null, 16],
        "\0".parent::class."\0".'storageProvider' => [parent::class, 'storageProvider', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'uploadedAt' => [parent::class, 'uploadedAt', null, 16],
        'altText' => [parent::class, 'altText', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'dimensions' => [parent::class, 'dimensions', null, 16],
        'fileSize' => [parent::class, 'fileSize', null, 16],
        'filename' => [parent::class, 'filename', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'mimeType' => [parent::class, 'mimeType', null, 16],
        'originalFilename' => [parent::class, 'originalFilename', null, 16],
        'ownerClient' => [parent::class, 'ownerClient', null, 16],
        'processingStatus' => [parent::class, 'processingStatus', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'storageKey' => [parent::class, 'storageKey', null, 16],
        'storageProvider' => [parent::class, 'storageProvider', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'uploadedAt' => [parent::class, 'uploadedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
