<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Backlink extends \App\Entity\Backlink implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'anchorText' => [parent::class, 'anchorText', null, 16],
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'context' => [parent::class, 'context', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'domainAuthority' => [parent::class, 'domainAuthority', null, 16],
        "\0".parent::class."\0".'firstSeen' => [parent::class, 'firstSeen', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isBlog' => [parent::class, 'isBlog', null, 16],
        "\0".parent::class."\0".'isNews' => [parent::class, 'isNews', null, 16],
        "\0".parent::class."\0".'isSocial' => [parent::class, 'isSocial', null, 16],
        "\0".parent::class."\0".'language' => [parent::class, 'language', null, 16],
        "\0".parent::class."\0".'lastSeen' => [parent::class, 'lastSeen', null, 16],
        "\0".parent::class."\0".'linkType' => [parent::class, 'linkType', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'pageAuthority' => [parent::class, 'pageAuthority', null, 16],
        "\0".parent::class."\0".'sourceDomain' => [parent::class, 'sourceDomain', null, 16],
        "\0".parent::class."\0".'sourceUrl' => [parent::class, 'sourceUrl', null, 16],
        "\0".parent::class."\0".'spamScore' => [parent::class, 'spamScore', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'targetDomain' => [parent::class, 'targetDomain', null, 16],
        "\0".parent::class."\0".'targetUrl' => [parent::class, 'targetUrl', null, 16],
        "\0".parent::class."\0".'tenantId' => [parent::class, 'tenantId', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'anchorText' => [parent::class, 'anchorText', null, 16],
        'clientId' => [parent::class, 'clientId', null, 16],
        'context' => [parent::class, 'context', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'domainAuthority' => [parent::class, 'domainAuthority', null, 16],
        'firstSeen' => [parent::class, 'firstSeen', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isBlog' => [parent::class, 'isBlog', null, 16],
        'isNews' => [parent::class, 'isNews', null, 16],
        'isSocial' => [parent::class, 'isSocial', null, 16],
        'language' => [parent::class, 'language', null, 16],
        'lastSeen' => [parent::class, 'lastSeen', null, 16],
        'linkType' => [parent::class, 'linkType', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'pageAuthority' => [parent::class, 'pageAuthority', null, 16],
        'sourceDomain' => [parent::class, 'sourceDomain', null, 16],
        'sourceUrl' => [parent::class, 'sourceUrl', null, 16],
        'spamScore' => [parent::class, 'spamScore', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'targetDomain' => [parent::class, 'targetDomain', null, 16],
        'targetUrl' => [parent::class, 'targetUrl', null, 16],
        'tenantId' => [parent::class, 'tenantId', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
