<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SeoMeta extends \App\Entity\SeoMeta implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        'canonicalUrl' => [parent::class, 'canonicalUrl', null, 4],
        'createdAt' => [parent::class, 'createdAt', null, 4],
        'entityId' => [parent::class, 'entityId', null, 4],
        'entityType' => [parent::class, 'entityType', null, 4],
        'id' => [parent::class, 'id', null, 16],
        'metaDescription' => [parent::class, 'metaDescription', null, 4],
        'openGraph' => [parent::class, 'openGraph', null, 4],
        'robots' => [parent::class, 'robots', null, 4],
        'tenantId' => [parent::class, 'tenantId', null, 4],
        'title' => [parent::class, 'title', null, 4],
        'twitterCard' => [parent::class, 'twitterCard', null, 4],
        'updatedAt' => [parent::class, 'updatedAt', null, 4],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
