<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AuditRun extends \App\Entity\AuditRun implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'completedAt' => [parent::class, 'completedAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'initiatedBy' => [parent::class, 'initiatedBy', null, 16],
        "\0".parent::class."\0".'intake' => [parent::class, 'intake', null, 16],
        "\0".parent::class."\0".'scope' => [parent::class, 'scope', null, 16],
        "\0".parent::class."\0".'startedAt' => [parent::class, 'startedAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'completedAt' => [parent::class, 'completedAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'initiatedBy' => [parent::class, 'initiatedBy', null, 16],
        'intake' => [parent::class, 'intake', null, 16],
        'scope' => [parent::class, 'scope', null, 16],
        'startedAt' => [parent::class, 'startedAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
