<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Subscription extends \App\Entity\Subscription implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null, 16],
        "\0".parent::class."\0".'autoRenew' => [parent::class, 'autoRenew', null, 16],
        "\0".parent::class."\0".'billingCycle' => [parent::class, 'billingCycle', null, 16],
        "\0".parent::class."\0".'cancelledAt' => [parent::class, 'cancelledAt', null, 16],
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'features' => [parent::class, 'features', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'nextBillingDate' => [parent::class, 'nextBillingDate', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'packageId' => [parent::class, 'packageId', null, 16],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null, 16],
        "\0".parent::class."\0".'startDate' => [parent::class, 'startDate', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'stripeCustomerId' => [parent::class, 'stripeCustomerId', null, 16],
        "\0".parent::class."\0".'stripeSubscriptionId' => [parent::class, 'stripeSubscriptionId', null, 16],
        "\0".parent::class."\0".'tenantId' => [parent::class, 'tenantId', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'amount' => [parent::class, 'amount', null, 16],
        'autoRenew' => [parent::class, 'autoRenew', null, 16],
        'billingCycle' => [parent::class, 'billingCycle', null, 16],
        'cancelledAt' => [parent::class, 'cancelledAt', null, 16],
        'clientId' => [parent::class, 'clientId', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'currency' => [parent::class, 'currency', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'features' => [parent::class, 'features', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'nextBillingDate' => [parent::class, 'nextBillingDate', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'packageId' => [parent::class, 'packageId', null, 16],
        'quantity' => [parent::class, 'quantity', null, 16],
        'startDate' => [parent::class, 'startDate', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'stripeCustomerId' => [parent::class, 'stripeCustomerId', null, 16],
        'stripeSubscriptionId' => [parent::class, 'stripeSubscriptionId', null, 16],
        'tenantId' => [parent::class, 'tenantId', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
