<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AuditConversionGoal extends \App\Entity\AuditConversionGoal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'baseline' => [parent::class, 'baseline', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'intake' => [parent::class, 'intake', null, 16],
        "\0".parent::class."\0".'kpi' => [parent::class, 'kpi', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'valuePerConversion' => [parent::class, 'valuePerConversion', null, 16],
        'baseline' => [parent::class, 'baseline', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'intake' => [parent::class, 'intake', null, 16],
        'kpi' => [parent::class, 'kpi', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'valuePerConversion' => [parent::class, 'valuePerConversion', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
