<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null, 16],
        "\0".parent::class."\0".'agency' => [parent::class, 'agency', null, 16],
        "\0".parent::class."\0".'auditFindings' => [parent::class, 'auditFindings', null, 16],
        "\0".parent::class."\0".'auditIntakes' => [parent::class, 'auditIntakes', null, 16],
        "\0".parent::class."\0".'auditRuns' => [parent::class, 'auditRuns', null, 16],
        "\0".parent::class."\0".'campaigns' => [parent::class, 'campaigns', null, 16],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'googleAnalytics' => [parent::class, 'googleAnalytics', null, 16],
        "\0".parent::class."\0".'googleBusinessProfile' => [parent::class, 'googleBusinessProfile', null, 16],
        "\0".parent::class."\0".'googleSearchConsole' => [parent::class, 'googleSearchConsole', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'industry' => [parent::class, 'industry', null, 16],
        "\0".parent::class."\0".'keywords' => [parent::class, 'keywords', null, 16],
        "\0".parent::class."\0".'leads' => [parent::class, 'leads', null, 16],
        "\0".parent::class."\0".'locations' => [parent::class, 'locations', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'oauthConnections' => [parent::class, 'oauthConnections', null, 16],
        "\0".parent::class."\0".'openPhoneIntegrations' => [parent::class, 'openPhoneIntegrations', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null, 16],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null, 16],
        "\0".parent::class."\0".'state' => [parent::class, 'state', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userAccess' => [parent::class, 'userAccess', null, 16],
        "\0".parent::class."\0".'websiteUrl' => [parent::class, 'websiteUrl', null, 16],
        'address' => [parent::class, 'address', null, 16],
        'agency' => [parent::class, 'agency', null, 16],
        'auditFindings' => [parent::class, 'auditFindings', null, 16],
        'auditIntakes' => [parent::class, 'auditIntakes', null, 16],
        'auditRuns' => [parent::class, 'auditRuns', null, 16],
        'campaigns' => [parent::class, 'campaigns', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'googleAnalytics' => [parent::class, 'googleAnalytics', null, 16],
        'googleBusinessProfile' => [parent::class, 'googleBusinessProfile', null, 16],
        'googleSearchConsole' => [parent::class, 'googleSearchConsole', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'industry' => [parent::class, 'industry', null, 16],
        'keywords' => [parent::class, 'keywords', null, 16],
        'leads' => [parent::class, 'leads', null, 16],
        'locations' => [parent::class, 'locations', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'oauthConnections' => [parent::class, 'oauthConnections', null, 16],
        'openPhoneIntegrations' => [parent::class, 'openPhoneIntegrations', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'postalCode' => [parent::class, 'postalCode', null, 16],
        'slug' => [parent::class, 'slug', null, 16],
        'state' => [parent::class, 'state', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userAccess' => [parent::class, 'userAccess', null, 16],
        'websiteUrl' => [parent::class, 'websiteUrl', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
