<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NewsletterSubscription extends \App\Entity\NewsletterSubscription implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'company' => [parent::class, 'company', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'interests' => [parent::class, 'interests', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'source' => [parent::class, 'source', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'subscribedAt' => [parent::class, 'subscribedAt', null, 16],
        "\0".parent::class."\0".'tenantId' => [parent::class, 'tenantId', null, 16],
        "\0".parent::class."\0".'unsubscribedAt' => [parent::class, 'unsubscribedAt', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'company' => [parent::class, 'company', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'interests' => [parent::class, 'interests', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'source' => [parent::class, 'source', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'subscribedAt' => [parent::class, 'subscribedAt', null, 16],
        'tenantId' => [parent::class, 'tenantId', null, 16],
        'unsubscribedAt' => [parent::class, 'unsubscribedAt', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
