<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AuditIntake extends \App\Entity\AuditIntake implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'cms' => [parent::class, 'cms', null, 16],
        "\0".parent::class."\0".'cmsVersion' => [parent::class, 'cmsVersion', null, 16],
        "\0".parent::class."\0".'competitors' => [parent::class, 'competitors', null, 16],
        "\0".parent::class."\0".'contactEmail' => [parent::class, 'contactEmail', null, 16],
        "\0".parent::class."\0".'contactName' => [parent::class, 'contactName', null, 16],
        "\0".parent::class."\0".'contactPhone' => [parent::class, 'contactPhone', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'gaPropertyId' => [parent::class, 'gaPropertyId', null, 16],
        "\0".parent::class."\0".'gbpLocationIds' => [parent::class, 'gbpLocationIds', null, 16],
        "\0".parent::class."\0".'goals' => [parent::class, 'goals', null, 16],
        "\0".parent::class."\0".'gscProperty' => [parent::class, 'gscProperty', null, 16],
        "\0".parent::class."\0".'gtmContainerId' => [parent::class, 'gtmContainerId', null, 16],
        "\0".parent::class."\0".'hasGoogleAnalytics' => [parent::class, 'hasGoogleAnalytics', null, 16],
        "\0".parent::class."\0".'hasGoogleBusinessProfile' => [parent::class, 'hasGoogleBusinessProfile', null, 16],
        "\0".parent::class."\0".'hasSearchConsole' => [parent::class, 'hasSearchConsole', null, 16],
        "\0".parent::class."\0".'hasTagManager' => [parent::class, 'hasTagManager', null, 16],
        "\0".parent::class."\0".'hostingProvider' => [parent::class, 'hostingProvider', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'keywords' => [parent::class, 'keywords', null, 16],
        "\0".parent::class."\0".'markets' => [parent::class, 'markets', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'paidChannels' => [parent::class, 'paidChannels', null, 16],
        "\0".parent::class."\0".'primaryServices' => [parent::class, 'primaryServices', null, 16],
        "\0".parent::class."\0".'requestedBy' => [parent::class, 'requestedBy', null, 16],
        "\0".parent::class."\0".'robotsTxtUrl' => [parent::class, 'robotsTxtUrl', null, 16],
        "\0".parent::class."\0".'sitemapXmlUrl' => [parent::class, 'sitemapXmlUrl', null, 16],
        "\0".parent::class."\0".'stagingUrl' => [parent::class, 'stagingUrl', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'subdomains' => [parent::class, 'subdomains', null, 16],
        "\0".parent::class."\0".'targetAudience' => [parent::class, 'targetAudience', null, 16],
        "\0".parent::class."\0".'techStack' => [parent::class, 'techStack', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'websiteUrl' => [parent::class, 'websiteUrl', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'cms' => [parent::class, 'cms', null, 16],
        'cmsVersion' => [parent::class, 'cmsVersion', null, 16],
        'competitors' => [parent::class, 'competitors', null, 16],
        'contactEmail' => [parent::class, 'contactEmail', null, 16],
        'contactName' => [parent::class, 'contactName', null, 16],
        'contactPhone' => [parent::class, 'contactPhone', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'gaPropertyId' => [parent::class, 'gaPropertyId', null, 16],
        'gbpLocationIds' => [parent::class, 'gbpLocationIds', null, 16],
        'goals' => [parent::class, 'goals', null, 16],
        'gscProperty' => [parent::class, 'gscProperty', null, 16],
        'gtmContainerId' => [parent::class, 'gtmContainerId', null, 16],
        'hasGoogleAnalytics' => [parent::class, 'hasGoogleAnalytics', null, 16],
        'hasGoogleBusinessProfile' => [parent::class, 'hasGoogleBusinessProfile', null, 16],
        'hasSearchConsole' => [parent::class, 'hasSearchConsole', null, 16],
        'hasTagManager' => [parent::class, 'hasTagManager', null, 16],
        'hostingProvider' => [parent::class, 'hostingProvider', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'keywords' => [parent::class, 'keywords', null, 16],
        'markets' => [parent::class, 'markets', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'paidChannels' => [parent::class, 'paidChannels', null, 16],
        'primaryServices' => [parent::class, 'primaryServices', null, 16],
        'requestedBy' => [parent::class, 'requestedBy', null, 16],
        'robotsTxtUrl' => [parent::class, 'robotsTxtUrl', null, 16],
        'sitemapXmlUrl' => [parent::class, 'sitemapXmlUrl', null, 16],
        'stagingUrl' => [parent::class, 'stagingUrl', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'subdomains' => [parent::class, 'subdomains', null, 16],
        'targetAudience' => [parent::class, 'targetAudience', null, 16],
        'techStack' => [parent::class, 'techStack', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'websiteUrl' => [parent::class, 'websiteUrl', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
