<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notification extends \App\Entity\Notification implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'actionLabel' => [parent::class, 'actionLabel', null, 16],
        "\0".parent::class."\0".'actionUrl' => [parent::class, 'actionUrl', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isRead' => [parent::class, 'isRead', null, 16],
        "\0".parent::class."\0".'message' => [parent::class, 'message', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'readAt' => [parent::class, 'readAt', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'actionLabel' => [parent::class, 'actionLabel', null, 16],
        'actionUrl' => [parent::class, 'actionUrl', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isRead' => [parent::class, 'isRead', null, 16],
        'message' => [parent::class, 'message', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'readAt' => [parent::class, 'readAt', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
