<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'agency' => [parent::class, 'agency', null, 16],
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'initiatedAuditRuns' => [parent::class, 'initiatedAuditRuns', null, 16],
        "\0".parent::class."\0".'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'oauthConnections' => [parent::class, 'oauthConnections', null, 16],
        "\0".parent::class."\0".'organization' => [parent::class, 'organization', null, 16],
        "\0".parent::class."\0".'passwordHash' => [parent::class, 'passwordHash', null, 16],
        "\0".parent::class."\0".'requestedAuditIntakes' => [parent::class, 'requestedAuditIntakes', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tenant' => [parent::class, 'tenant', null, 16],
        "\0".parent::class."\0".'tokens' => [parent::class, 'tokens', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'userAccess' => [parent::class, 'userAccess', null, 16],
        'agency' => [parent::class, 'agency', null, 16],
        'clientId' => [parent::class, 'clientId', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'firstName' => [parent::class, 'firstName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'initiatedAuditRuns' => [parent::class, 'initiatedAuditRuns', null, 16],
        'lastLoginAt' => [parent::class, 'lastLoginAt', null, 16],
        'lastName' => [parent::class, 'lastName', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'oauthConnections' => [parent::class, 'oauthConnections', null, 16],
        'organization' => [parent::class, 'organization', null, 16],
        'passwordHash' => [parent::class, 'passwordHash', null, 16],
        'requestedAuditIntakes' => [parent::class, 'requestedAuditIntakes', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tenant' => [parent::class, 'tenant', null, 16],
        'tokens' => [parent::class, 'tokens', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'userAccess' => [parent::class, 'userAccess', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
