<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OpenPhoneMessageLog extends \App\Entity\OpenPhoneMessageLog implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'attachments' => [parent::class, 'attachments', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'direction' => [parent::class, 'direction', null, 16],
        "\0".parent::class."\0".'fromNumber' => [parent::class, 'fromNumber', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'integration' => [parent::class, 'integration', null, 16],
        "\0".parent::class."\0".'isFollowUpRequired' => [parent::class, 'isFollowUpRequired', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null, 16],
        "\0".parent::class."\0".'openPhoneMessageId' => [parent::class, 'openPhoneMessageId', null, 16],
        "\0".parent::class."\0".'sentAt' => [parent::class, 'sentAt', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'toNumber' => [parent::class, 'toNumber', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'attachments' => [parent::class, 'attachments', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'content' => [parent::class, 'content', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'direction' => [parent::class, 'direction', null, 16],
        'fromNumber' => [parent::class, 'fromNumber', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'integration' => [parent::class, 'integration', null, 16],
        'isFollowUpRequired' => [parent::class, 'isFollowUpRequired', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'notes' => [parent::class, 'notes', null, 16],
        'openPhoneMessageId' => [parent::class, 'openPhoneMessageId', null, 16],
        'sentAt' => [parent::class, 'sentAt', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'toNumber' => [parent::class, 'toNumber', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
