<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocumentTemplate extends \App\Entity\DocumentTemplate implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'content' => [parent::class, 'content', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'documents' => [parent::class, 'documents', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'requiresSignature' => [parent::class, 'requiresSignature', null, 16],
        "\0".parent::class."\0".'signatureFields' => [parent::class, 'signatureFields', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'usageCount' => [parent::class, 'usageCount', null, 16],
        "\0".parent::class."\0".'variables' => [parent::class, 'variables', null, 16],
        'content' => [parent::class, 'content', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'documents' => [parent::class, 'documents', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'requiresSignature' => [parent::class, 'requiresSignature', null, 16],
        'signatureFields' => [parent::class, 'signatureFields', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'usageCount' => [parent::class, 'usageCount', null, 16],
        'variables' => [parent::class, 'variables', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
