<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Review extends \App\Entity\Review implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'clientId' => [parent::class, 'clientId', null, 16],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isResponse' => [parent::class, 'isResponse', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'platform' => [parent::class, 'platform', null, 16],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null, 16],
        "\0".parent::class."\0".'response' => [parent::class, 'response', null, 16],
        "\0".parent::class."\0".'responseDate' => [parent::class, 'responseDate', null, 16],
        "\0".parent::class."\0".'reviewDate' => [parent::class, 'reviewDate', null, 16],
        "\0".parent::class."\0".'reviewId' => [parent::class, 'reviewId', null, 16],
        "\0".parent::class."\0".'reviewerImage' => [parent::class, 'reviewerImage', null, 16],
        "\0".parent::class."\0".'reviewerName' => [parent::class, 'reviewerName', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'tenantId' => [parent::class, 'tenantId', null, 16],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'clientId' => [parent::class, 'clientId', null, 16],
        'content' => [parent::class, 'content', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isResponse' => [parent::class, 'isResponse', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'platform' => [parent::class, 'platform', null, 16],
        'rating' => [parent::class, 'rating', null, 16],
        'response' => [parent::class, 'response', null, 16],
        'responseDate' => [parent::class, 'responseDate', null, 16],
        'reviewDate' => [parent::class, 'reviewDate', null, 16],
        'reviewId' => [parent::class, 'reviewId', null, 16],
        'reviewerImage' => [parent::class, 'reviewerImage', null, 16],
        'reviewerName' => [parent::class, 'reviewerName', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'tenantId' => [parent::class, 'tenantId', null, 16],
        'title' => [parent::class, 'title', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
