<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OpenPhoneIntegration extends \App\Entity\OpenPhoneIntegration implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'autoLogCalls' => [parent::class, 'autoLogCalls', null, 16],
        "\0".parent::class."\0".'autoLogMessages' => [parent::class, 'autoLogMessages', null, 16],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'displayName' => [parent::class, 'displayName', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isDefault' => [parent::class, 'isDefault', null, 16],
        "\0".parent::class."\0".'metadata' => [parent::class, 'metadata', null, 16],
        "\0".parent::class."\0".'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        "\0".parent::class."\0".'settings' => [parent::class, 'settings', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'syncContacts' => [parent::class, 'syncContacts', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'autoLogCalls' => [parent::class, 'autoLogCalls', null, 16],
        'autoLogMessages' => [parent::class, 'autoLogMessages', null, 16],
        'client' => [parent::class, 'client', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'displayName' => [parent::class, 'displayName', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isDefault' => [parent::class, 'isDefault', null, 16],
        'metadata' => [parent::class, 'metadata', null, 16],
        'phoneNumber' => [parent::class, 'phoneNumber', null, 16],
        'settings' => [parent::class, 'settings', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'syncContacts' => [parent::class, 'syncContacts', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
