<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnotatedAppEntityContentItemApiPlatformDoctrineOrmFilterOrderFilterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'annotated_app_entity_content_item_api_platform_doctrine_orm_filter_order_filter' shared autowired service.
     *
     * @return \ApiPlatform\Doctrine\Orm\Filter\OrderFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['annotated_app_entity_content_item_api_platform_doctrine_orm_filter_order_filter'] = new \ApiPlatform\Doctrine\Orm\Filter\OrderFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), 'order', ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ['createdAt' => 'DESC', 'publishedAt' => 'DESC', 'title' => 'ASC'], ($container->privates['api_platform.hydra.name_converter.hydra_prefix'] ?? self::getApiPlatform_Hydra_NameConverter_HydraPrefixService($container)), NULL);
    }
}
