<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateClientCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\CreateClientCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\CreateClientCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:create-client', [], 'Create a new client (law firm)', false, #[\Closure(name: 'App\\Command\\CreateClientCommand')] fn (): \App\Command\CreateClientCommand => ($container->privates['App\\Command\\CreateClientCommand'] ?? $container->load('getCreateClientCommandService')));
    }
}
