<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentVersionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DocumentVersionRepository' shared autowired service.
     *
     * @return \App\Repository\DocumentVersionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DocumentVersionRepository'] = new \App\Repository\DocumentVersionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
