<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateSampleDataCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\GenerateSampleDataCommand' shared autowired service.
     *
     * @return \App\Command\GenerateSampleDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\GenerateSampleDataCommand'] = $instance = new \App\Command\GenerateSampleDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:generate-sample-data');
        $instance->setDescription('Generate sample data for the client dashboard (leads, campaigns, case studies)');

        return $instance;
    }
}
