<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportTulsaAttorneysCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\ImportTulsaAttorneysCommand' shared autowired service.
     *
     * @return \App\Command\ImportTulsaAttorneysCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\ImportTulsaAttorneysCommand'] = $instance = new \App\Command\ImportTulsaAttorneysCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:import-tulsa-attorneys');
        $instance->setDescription('Import mock Tulsa attorneys data for testing');

        return $instance;
    }
}
