<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadgenControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\LeadgenController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\LeadgenController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\LeadgenController'] = $instance = new \App\Controller\Api\V1\LeadgenController(new \App\Service\LeadgenExecutionService(($container->privates['App\\Repository\\LeadRepository'] ?? $container->load('getLeadRepositoryService')), ($container->privates['App\\Repository\\LeadSourceRepository'] ?? $container->load('getLeadSourceRepositoryService')), ($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\LeadgenController', $container));

        return $instance;
    }
}
