<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVerifyTulsaLeadsCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\VerifyTulsaLeadsCommand' shared autowired service.
     *
     * @return \App\Command\VerifyTulsaLeadsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\VerifyTulsaLeadsCommand'] = $instance = new \App\Command\VerifyTulsaLeadsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\LeadRepository'] ?? $container->load('getLeadRepositoryService')));

        $instance->setName('app:verify-tulsa-leads');
        $instance->setDescription('Verify Tulsa attorneys leads are properly imported');

        return $instance;
    }
}
