<?php

namespace ContainerXGPGXlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhooksControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Api\V1\WebhooksController' shared autowired service.
     *
     * @return \App\Controller\Api\V1\WebhooksController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Api\\V1\\WebhooksController'] = $instance = new \App\Controller\Api\V1\WebhooksController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\Api\\V1\\WebhooksController', $container));

        return $instance;
    }
}
