services:
  # PHP Application
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: audit-service-php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
    depends_on:
      - postgres
      - redis
      - minio
      - chrome
    networks:
      - audit-network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: audit-service-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - audit-network

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: audit-service-postgres
    environment:
      POSTGRES_DB: audit_service
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: audit_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - audit-network

  # Redis Cache & Message Queue
  redis:
    image: redis:7-alpine
    container_name: audit-service-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - audit-network

  # MinIO Object Storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: audit-service-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - audit-network

  # Headless Chrome for Screenshots & Lighthouse
  chrome:
    image: chromedp/headless-shell:latest
    container_name: audit-service-chrome
    environment:
      - CHROME_HEADLESS_URL=http://chrome:9222
    ports:
      - "9222:9222"
    networks:
      - audit-network

  # Worker Process
  worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: audit-service-worker
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
    command: php bin/console messenger:consume crawl lighthouse analyze aggregate report notify --time-limit=3600
    depends_on:
      - postgres
      - redis
      - minio
      - chrome
    networks:
      - audit-network

  # Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: audit-service-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - audit-network

  # Prometheus Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: audit-service-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - audit-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  audit-network:
    driver: bridge
