<?php

namespace ContainerZihELGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentTemplateRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\DocumentTemplateRepository' shared autowired service.
     *
     * @return \App\Repository\DocumentTemplateRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\DocumentTemplateRepository'] = new \App\Repository\DocumentTemplateRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
