<?php

namespace ContainerZihELGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioControllersendSmsToClientService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.axWvN5H.App\Controller\Api\V1\TwilioController::sendSmsToClient()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.axWvN5H'] ?? $container->load('get_ServiceLocator_AxWvN5HService'));

        if (isset($container->privates['.service_locator.axWvN5H.App\\Controller\\Api\\V1\\TwilioController::sendSmsToClient()'])) {
            return $container->privates['.service_locator.axWvN5H.App\\Controller\\Api\\V1\\TwilioController::sendSmsToClient()'];
        }

        return $container->privates['.service_locator.axWvN5H.App\\Controller\\Api\\V1\\TwilioController::sendSmsToClient()'] = $a->withContext('App\\Controller\\Api\\V1\\TwilioController::sendSmsToClient()', $container);
    }
}
