<?php

namespace ContainerZihELGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestTulsaLeadsAPICommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\TestTulsaLeadsAPICommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\TestTulsaLeadsAPICommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:test-tulsa-leads-api', [], 'Test Tulsa attorneys leads API response format', false, #[\Closure(name: 'App\\Command\\TestTulsaLeadsAPICommand')] fn (): \App\Command\TestTulsaLeadsAPICommand => ($container->privates['App\\Command\\TestTulsaLeadsAPICommand'] ?? $container->load('getTestTulsaLeadsAPICommandService')));
    }
}
