<?php

namespace ContainerZihELGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestTwilioCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\TestTwilioCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\TestTwilioCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:test-twilio', [], 'Test Twilio integration by making a call to 786-213-3333', false, #[\Closure(name: 'App\\Command\\TestTwilioCommand')] fn (): \App\Command\TestTwilioCommand => ($container->privates['App\\Command\\TestTwilioCommand'] ?? $container->load('getTestTwilioCommandService')));
    }
}
