<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ65J2Sc\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ65J2Sc/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerJ65J2Sc.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerJ65J2Sc\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerJ65J2Sc\App_KernelTestContainer([
    'container.build_hash' => 'J65J2Sc',
    'container.build_id' => 'db207389',
    'container.build_time' => 1756323849,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ65J2Sc');
